---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004:                        # Unordered list style
  style: consistent
MD005: true
MD009:
  br_spaces: 2
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 2000            # Line length 80 is far to short
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: true                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading

#################
# Rules by tags #
#################
blank_lines: true  # Error on blank lines
code: true
images: true
links: true
url: true
whitespace: true
atx: true
blockquote: true
bullet: true
emphasis: true
headers: true
headings: true
indentation: true
ol: true
ul: true
spaces: true
spellings: true
