name: Assign

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]

jobs:
  slash_assign:
    # If the acton was triggered by a new comment that starts with `/Rotten`
    # or a on a schedule
    if: >
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/Rotten')) ||
      github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: vybhav72954/Slash-Assign@v1
        with:
          required_label: Up-For-Grab
          assigned_label: Assigned
          days_until_warning: 7
          days_until_unassign: 14
          stale_assignment_label: Open
          
