name: Assign

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]

jobs:
  slash_assign:
    # If the acton was triggered by a new comment that starts with `/Rotten`
    # or a on a schedule
    if: >
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/Rotten')) ||
      github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: JasonEtco/slash-assign-action@v1
        with:
          required_label: Up-For-Grab
          assigned_label: Assigned
          days_until_warning: 1
          days_until_unassign: 1
          stale_assignment_label: Up-For-Grab
          assigned_comment: This issue [has been assigned]({{ comment.html_url }}) to {{ comment.user.login }}! It will be unassigned if it isn't closed within {{ totalDays }} days. Best Of Luck!!!!!
          warning_comment: @{{ assignee.login }}, How are you, this issue hasnt seen any activity in {{ inputs.days_until_warning }} days. We are sorry but in {{ inputs.days_until_unassign }} days it would be unassingned, Best of Luck, You Got this.