name: "Issue Labeler"
on:
  issues:
    types: [open]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issues_labeler.yml
          enable-versioned-regex: 0