name: PR_Labeler
on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Run Action
        uses: anushkrishnav/PR-Line-Labeler@main
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          repo: vybhav72954/Git-Action
