name: PyLint Runner

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/**.py'
      - '!.github/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Paths Changes Filter
      uses: dorny/paths-filter@v2.5.1
      id: changes
      with:
        filters: |
        python: path
          - '**/**.py'

    #- name: Detect Files
    #  uses: dorny/paths-filter@v2
    #  id: filter
    #  with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command line argument list in linux shell
     #   list-files: shell

        # In this example changed files will be checked by linter.
        # It doesn't make sense to lint deleted files.
        # Therefore we specify we are only interested in added or modified files.
      #  filters: |
       # Python:
        #  - added|modified: '**.py'


    #- name: PyLint Python
    #  if: ${{ steps.filter.outputs.python == 'true' }}
    #  run: python pyLint.py --path ${{ steps.filter.outputs.python_files }} --threshold 1.5

    - name: Run lint check
      env:
        FILES: '${{ steps.files.outputs.files_updated }} ${{ steps.files.outputs.files_created }}'
      run: python pyLint.py --path $FILE --threshold 1.5

