
name: Spellcheck Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.11.0
    - uses: dorny/paths-filter@v2.6.0
      id: filter
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in linux shell
        list-files: shell

        # In this example changed files will be checked by linter.
        # It doesn't make sense to lint deleted files.
        # Therefore we specify we are only interested in added or modified files.
        filters: |
          markdown:
            - added|modified: '*.md'